services:
  - type: web
    name: taskora-work
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
      - key: COOKIE_SECURE
        value: "1"
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_WEBHOOK_HASH
        sync: false
